const folderPathActionTypes = {
  FETCH_FOLDER_PATH_START: 'FETCH_FOLDER_PATH_START',
  FETCH_FOLDER_PATH_SUCCESS: 'FETCH_FOLDER_PATH_SUCCESS',
  FETCH_FOLDER_PATH_FAILURE: 'FETCH_FOLDER_PATH_FAILURE'
};

export default folderPathActionTypes;
