const folderTreeActionTypes = {
  FETCH_FOLDER_TREE_START: 'FETCH_FOLDER_TREE_START',
  FETCH_FOLDER_TREE_SUCCESS: 'FETCH_FOLDER_TREE_SUCCESS',
  FETCH_FOLDER_TREE_FALIURE: 'FETCH_FOLDER_TREE_FALIURE'
};

export default folderTreeActionTypes;
