const UiActionTypes = {
  TOGGLE_DROPDOWN_EDIT: 'TOGGLE_DROPDOWN_EDIT',
  TOGGLE_MODAL_NEW: 'TOGGLE_MODAL_NEW',
  TOGGLE_MODAL_RENAME: 'TOGGLE_MODAL_RENAME',
  TOGGLE_MODAL_COPY: 'TOGGLE_MODAL_COPY',
  TOGGLE_MODAL_MOVE: 'TOGGLE_MODAL_MOVE',
  SET_DROPDOWN_POS: 'SET_DROPDOWN_POS'
};

export default UiActionTypes;
