const currentResourceActionTypes = {
  SET_CURRENT_RESOURCE: 'SET_CURRENT_RESOURCE',
  CLEAR_CURRENT_RESOURCE: 'CLEAR_CURRENT_RESOURCE',
  SET_TARGET_FOLDER_ID: 'SET_TARGET_FOLDER_ID'
};

export default currentResourceActionTypes;
