const fileLibraryActionTypes = {
  FETCH_FILELIBRARY_START: 'FETCH_FILELIBRARY_START',
  FETCH_FILELIBRARY_SUCCESS: 'FETCH_FILELIBRARY_SUCCESS',
  FETCH_FILELIBRARY_FAILURE: 'FETCH_FILELIBRARY_FAILURE'
};

export default fileLibraryActionTypes;
